name: 🐳 Docker Image
run-name: "Build and Deploy Docker Image launched by @${{ github.actor }}"

on:
  push:
     branches: [ main ]

jobs:
  test-and-deploy:
    name: 🐳 Build and Push
    runs-on: ubuntu-latest

    steps:
      - name: 🧹 Clean up pre-installed tools
        run: |
          rm -rf /usr/share/dotnet
          rm -rf /opt/ghc
          rm -rf "/usr/local/share/boost"
          rm -rf "$AGENT_TOOLSDIRECTORY"

      - name: ⚙️ Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: 🔐 Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: 🔧 Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 🐳 Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ github.sha }},ghcr.io/${{ github.repository }}:latest
          secrets: |
            HF_TOKEN=${{ secrets.HF_TOKEN }}
